AUGMENTATION: True

IMAGE_SIZE: [32, 32, 3]

BATCH_SIZE: 64

EPOCHS: 10

CLASSES: 10

LEARNING_RATE: 0.0005

WEIGHT_DECAY: 0.0001

VALIDATION_SPLIT: 0.1

ROTATION_RANGE: 15

WIDTH_SHIFT_RANGE: 0.12

HEIGHT_SHIFT_RANGE: 0.12

HORIZONTAL_FLIP: True

ZOOM_RANGE: 0.1

BRIGHTNESS_RANGE: [0.9, 1.1]

SHEAR_RANGE: 0.1

CHANNEL_SHIFT_RANGE: 0.1

REDUCE_LR_FACTOR: 0.5

REDUCE_LR_PATIENCE: 10

MIN_LEARNING_RATE: 0.00001

EARLY_STOPPING_PATIENCE: 40